apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-quarkus
  labels:
    app: hello-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-quarkus
  template:
    metadata:
      labels:
        app: hello-quarkus
    spec:
      containers:
        - name: hello-quarkus
          image: hello-quarkus:1.0.0
          imagePullPolicy: Never     # 🔥 evita que Kubernetes intente descargar la imagen
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-quarkus
spec:
  selector:
    app: hello-quarkus
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
